[tool.poetry]
name = "oxtapus"
version = "0.2.5"
description = ""
authors = ["Yaghoub Ghadri <y.ghaderi@outlook.com>"]
readme = "README.md"
repository = "https://github.com/yghaderi/oxtapus"

[tool.coverage.run]
source = ["oxtapus"]
branch = true

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
jdatetime = "^4.1.1"
hazm = "^0.9.3"
aiohttp = "^3.8.5"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
html5lib = "^1.1"
lxml = "^4.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



