[tool.poetry]
name = "metafid-data"
version = "0.1.3"
description = ""
authors = ["Yaghoub Ghadri <y.ghaderi@outlook.com>"]
readme = "README.md"
repository = "https://github.com/yghaderi/metafid-data"

packages = [
    {include="mf_data", from="src"},
    {include="mf_data/ise", from="src"},
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
jdatetime = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



