[tool.poetry]
name = "oxtapus"
version = "0.3.4"
description = ""
authors = ["Yaghoub Ghadri <y.ghaderi@outlook.com>"]
readme = "README.md"
repository = "https://github.com/yghaderi/oxtapus"

[tool.coverage.run]
source = ["oxtapus"]
branch = true

[tool.poetry.dependencies]
python = "^3.11"
polars = "^1.0.0"
tarix = "^0.1.1"
httpx = "^0.25.0"
tenacity = "^8.2.3"
pydantic = "^2.5.3"
requests = "^2.32.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
root="valpy"
venvPath = "."
venv = ".venv"
